### ISSUE TITLE
Improve leaderboard

### ISSUE THREAD

**Issue by Fidge123** [Fidge123/tippspiel#4]
- [x] Make it easier to access for mobile view => extra page

Additional info:
- Leaderboard:
  - [x] Name, Ranking, Total Points, Correct bets (absolute / percentage)
  - [x] Number of times you got 3/2/1 extra points
  - [ ] Distance between bets and correct results (absolute / average)
  - [ ] Best team (most points total+average) / worst team (least points total+average) (show logo)

**Comment by Julikoo** [comment]
First ideas for easier access: 
https://www.figma.com/file/WLJQYUH0mIyQsanluF6Br5/Tippspiel?node-id=10%3A34
